Feature/static code analysis
axthosarouris/dotnet-webapp pull request #28
Opened 2022-07-28 13:14 UTC by NikosNe

Addresses #22

2022-07-30 06:56 UTC, axthosarouris commented
Approved if the conflicts are resolved

2022-08-04 14:42 UTC, NikosNe commented
We have a "it works on my machine" case. Are you getting the same error as the one in the check?

2022-08-04 20:55 UTC, axthosarouris commented
> We have a "it works on my machine" case. Are you getting the same error as the one in the check?

It works on me as well

2022-08-04 22:07 UTC, axthosarouris requested changes

2022-08-04 22:08 UTC, axthosarouris commented on PracticeWebApp/Startup.cs
> +                }
I have also created a PR to your PR, just to make sure that the tests run :)

2022-10-15 20:03 UTC, merged